Decision Tree Classification

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("/content/titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
inputs = df.drop('Survived',axis='columns')

In [6]:
target = df['Survived']

In [7]:
from sklearn.preprocessing import LabelEncoder
le_pclass = LabelEncoder()
le_sex = LabelEncoder()
le_age = LabelEncoder()
le_fare = LabelEncoder()

In [8]:
inputs['pclass_n'] = le_pclass.fit_transform(inputs['Pclass'])
inputs['sex_n'] = le_sex.fit_transform(inputs['Sex'])
inputs['age_n'] = le_age.fit_transform(inputs['Age'])
inputs['fare_n'] = le_fare.fit_transform(inputs['Fare'])

In [9]:
inputs

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,pclass_n,sex_n,age_n,fare_n
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,1,28,18
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,0,51,207
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,2,0,34,41
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0,0,47,189
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,2,1,47,43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1,1,35,85
887,888,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0,0,24,153
888,889,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,2,0,88,131
889,890,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0,1,34,153
890,891,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,2,1,42,30

In [10]:
print("Pclass Encoding Mapping:", dict(zip(le_pclass.classes_, range(len(le_pclass.classes_)))))

Pclass Encoding Mapping: {1: 0, 2: 1, 3: 2}

In [11]:
print("Sex Encoding Mapping:", dict(zip(le_sex.classes_, range(len(le_sex.classes_)))))

Sex Encoding Mapping: {'female': 0, 'male': 1}

In [12]:
print("Age Encoding Mapping:", dict(zip(le_age.classes_, range(len(le_age.classes_)))))

Age Encoding Mapping: {0.42: 0, 0.67: 1, 0.75: 2, 0.83: 3, 0.92: 4, 1.0: 5, 2.0: 6, 3.0: 7, 4.0: 8, 5.0: 9, 6.0: 10, 7.0: 11, 8.0: 12, 9.0: 13, 10.0: 14, 11.0: 15, 12.0: 16, 13.0: 17, 14.0: 18, 14.5: 19, 15.0: 20, 16.0: 21, 17.0: 22, 18.0: 23, 19.0: 24, 20.0: 25, 20.5: 26, 21.0: 27, 22.0: 28, 23.0: 29, 23.5: 30, 24.0: 31, 24.5: 32, 25.0: 33, 26.0: 34, 27.0: 35, 28.0: 36, 28.5: 37, 29.0: 38, 30.0: 39, 30.5: 40, 31.0: 41, 32.0: 42, 32.5: 43, 33.0: 44, 34.0: 45, 34.5: 46, 35.0: 47, 36.0: 48, 36.5: 49, 37.0: 50, 38.0: 51, 39.0: 52, 40.0: 53, 40.5: 54, 41.0: 55, 42.0: 56, 43.0: 57, 44.0: 58, 45.0: 59, 45.5: 60, 46.0: 61, 47.0: 62, 48.0: 63, 49.0: 64, 50.0: 65, 51.0: 66, 52.0: 67, 53.0: 68, 54.0: 69, 55.0: 70, 55.5: 71, 56.0: 72, 57.0: 73, 58.0: 74, 59.0: 75, 60.0: 76, 61.0: 77, 62.0: 78, 63.0: 79, 64.0: 80, 65.0: 81, 66.0: 82, 70.0: 83, 70.5: 84, 71.0: 85, 74.0: 86, 80.0: 87, nan: 88}

In [13]:
print("Fare Encoding Mapping:", dict(zip(le_fare.classes_, range(len(le_fare.classes_)))))

Fare Encoding Mapping: {0.0: 0, 4.0125: 1, 5.0: 2, 6.2375: 3, 6.4375: 4, 6.45: 5, 6.4958: 6, 6.75: 7, 6.8583: 8, 6.95: 9, 6.975: 10, 7.0458: 11, 7.05: 12, 7.0542: 13, 7.125: 14, 7.1417: 15, 7.225: 16, 7.2292: 17, 7.25: 18, 7.3125: 19, 7.4958: 20, 7.5208: 21, 7.55: 22, 7.6292: 23, 7.65: 24, 7.725: 25, 7.7292: 26, 7.7333: 27, 7.7375: 28, 7.7417: 29, 7.75: 30, 7.775: 31, 7.7875: 32, 7.7958: 33, 7.8: 34, 7.8292: 35, 7.8542: 36, 7.875: 37, 7.8792: 38, 7.8875: 39, 7.8958: 40, 7.925: 41, 8.0292: 42, 8.05: 43, 8.1125: 44, 8.1375: 45, 8.1583: 46, 8.3: 47, 8.3625: 48, 8.4042: 49, 8.4333: 50, 8.4583: 51, 8.5167: 52, 8.6542: 53, 8.6625: 54, 8.6833: 55, 8.7125: 56, 8.85: 57, 9.0: 58, 9.2167: 59, 9.225: 60, 9.35: 61, 9.475: 62, 9.4833: 63, 9.5: 64, 9.5875: 65, 9.825: 66, 9.8375: 67, 9.8417: 68, 9.8458: 69, 10.1708: 70, 10.4625: 71, 10.5: 72, 10.5167: 73, 11.1333: 74, 11.2417: 75, 11.5: 76, 12.0: 77, 12.275: 78, 12.2875: 79, 12.35: 80, 12.475: 81, 12.525: 82, 12.65: 83, 12.875: 84, 13.0: 85, 13.4167: 86, 13.5: 87, 13.7917: 88, 13.8583: 89, 13.8625: 90, 14.0: 91, 14.1083: 92, 14.4: 93, 14.4542: 94, 14.4583: 95, 14.5: 96, 15.0: 97, 15.0458: 98, 15.05: 99, 15.1: 100, 15.2458: 101, 15.5: 102, 15.55: 103, 15.7417: 104, 15.75: 105, 15.85: 106, 15.9: 107, 16.0: 108, 16.1: 109, 16.7: 110, 17.4: 111, 17.8: 112, 18.0: 113, 18.75: 114, 18.7875: 115, 19.2583: 116, 19.5: 117, 19.9667: 118, 20.2125: 119, 20.25: 120, 20.525: 121, 20.575: 122, 21.0: 123, 21.075: 124, 21.6792: 125, 22.025: 126, 22.3583: 127, 22.525: 128, 23.0: 129, 23.25: 130, 23.45: 131, 24.0: 132, 24.15: 133, 25.4667: 134, 25.5875: 135, 25.925: 136, 25.9292: 137, 26.0: 138, 26.25: 139, 26.2833: 140, 26.2875: 141, 26.3875: 142, 26.55: 143, 27.0: 144, 27.7208: 145, 27.75: 146, 27.9: 147, 28.5: 148, 28.7125: 149, 29.0: 150, 29.125: 151, 29.7: 152, 30.0: 153, 30.0708: 154, 30.5: 155, 30.6958: 156, 31.0: 157, 31.275: 158, 31.3875: 159, 32.3208: 160, 32.5: 161, 33.0: 162, 33.5: 163, 34.0208: 164, 34.375: 165, 34.6542: 166, 35.0: 167, 35.5: 168, 36.75: 169, 37.0042: 170, 38.5: 171, 39.0: 172, 39.4: 173, 39.6: 174, 39.6875: 175, 40.125: 176, 41.5792: 177, 42.4: 178, 46.9: 179, 47.1: 180, 49.5: 181, 49.5042: 182, 50.0: 183, 50.4958: 184, 51.4792: 185, 51.8625: 186, 52.0: 187, 52.5542: 188, 53.1: 189, 55.0: 190, 55.4417: 191, 55.9: 192, 56.4958: 193, 56.9292: 194, 57.0: 195, 57.9792: 196, 59.4: 197, 61.175: 198, 61.3792: 199, 61.9792: 200, 63.3583: 201, 65.0: 202, 66.6: 203, 69.3: 204, 69.55: 205, 71.0: 206, 71.2833: 207, 73.5: 208, 75.25: 209, 76.2917: 210, 76.7292: 211, 77.2875: 212, 77.9583: 213, 78.2667: 214, 78.85: 215, 79.2: 216, 79.65: 217, 80.0: 218, 81.8583: 219, 82.1708: 220, 83.1583: 221, 83.475: 222, 86.5: 223, 89.1042: 224, 90.0: 225, 91.0792: 226, 93.5: 227, 106.425: 228, 108.9: 229, 110.8833: 230, 113.275: 231, 120.0: 232, 133.65: 233, 134.5: 234, 135.6333: 235, 146.5208: 236, 151.55: 237, 153.4625: 238, 164.8667: 239, 211.3375: 240, 211.5: 241, 221.7792: 242, 227.525: 243, 247.5208: 244, 262.375: 245, 263.0: 246, 512.3292: 247}

In [19]:
inputs_n = inputs_n.drop(['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'], axis=1)

In [20]:
inputs_n

     pclass_n  sex_n  age_n  fare_n
0           2      1     28      18
1           0      0     51     207
2           2      0     34      41
3           0      0     47     189
4           2      1     47      43
..        ...    ...    ...     ...
886         1      1     35      85
887         0      0     24     153
888         2      0     88     131
889         0      1     34     153
890         2      1     42      30

[891 rows x 4 columns]

In [16]:
target

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [17]:
from sklearn import tree
model = tree.DecisionTreeClassifier()

In [21]:
model.fit(inputs_n, target)

DecisionTreeClassifier()

In [22]:
model.score(inputs_n,target)

0.9797979797979798

In [24]:
model.predict([[2,1,47,43]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])